[package]
name = "cargo-machete"
edition = "2018"
version = "0.1.0"
authors = []
keywords = []
categories = []

[dependencies]
cargo_toml = "0.10.0"
grep = "0.2.8"
log = "0.4.14"
pretty_env_logger = "0.4.0"
toml = "0.5.8"
walkdir = "2.3.2"
serde = "1.0.130"
serde_json = "1.0.67"
anyhow = "1.0.44"
